<?php

/*
 * Implements hook_apachesolr_index_document_build_ENTITY_TYPE
 */
function apachesolr_onesearch_apachesolr_index_document_build_user($document, $entity) {
  try {
    # Add profile picture uri when indexing users
    $my_user = entity_metadata_wrapper('user', $entity);
    $pic_uri = file_create_url( $my_user->value()->picture->uri);
    if("" != $pic_uri) {
      $document->addField('ss_picture', $pic_uri);
    }
  }
  catch (EntityMetadataWrapperException $e) {
    watchdog(
      'apachesolr_onesearch',
      'EntityMetadataWrapper exception in %function() <pre>@trace</pre>',
      array('%function' => __FUNCTION__, '@trace' => $e->getTraceAsString()),
      WATCHDOG_ERROR
    );
  }
}

/*
 * Implements hook_apachesolr_ENTITY_TYPE_exclude
 */
function apachesolr_onesearch_apachesolr_user_exclude($entity_id,  $row, $env_id) {
  try {
    # Filter out users that don't have a title
    $my_user = entity_metadata_wrapper('user', $entity_id);
    $my_title = $my_user->field_title[0]->value() ;
    $exclude = ! isset($my_title);
    return $exclude;
  }
  catch (EntityMetadataWrapperException $e) {
    watchdog(
      'apachesolr_onesearch',
      'EntityMetadataWrapper exception in %function() <pre>@trace</pre>',
      array('%function' => __FUNCTION__, '@trace' => $e->getTraceAsString()),
      WATCHDOG_ERROR
    );
  }
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function apachesolr_onesearch_block_info(){
    $blocks = array();
    $blocks['onesearch_search'] = array(
        'info' => t('One Search'),
    );
    return $blocks;
}


/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function apachesolr_onesearch_block_view($delta=''){
    switch ($delta) {
      case 'onesearch_search':
        $variables = array();
        $block = array();
        $block['subject'] = "Discover!";
        $block['content'] = theme('onesearch_search', $variables);
        break;
    }
    return $block;
}

/**
 * Implementation of hook_theme
 */
function apachesolr_onesearch_theme() {
  return array(
    'onesearch_search' => array(
      'template' => 'templates/onesearch-search',
      'variables' => array(),
    ),
  );
}
